# Generated by Django 4.2.1 on 2023-05-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
