# Generated by Django 4.2.1 on 2023-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_remove_shippingaddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='apartament',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
